### PR TITLE
Fix cast_to_mathesar_money

### LINKED ISSUE #3954: Couldn't cast a text column to money type
## Description

https://github.com/user-attachments/assets/8c002067-cba8-4775-8427-4fdd1a1719c3

## Expected behavior

Type casting should work.

## To Reproduce

- Try to import a CSV with numeric values
- Notice that type inference works as expected and infers the numeric column as type `Number`
- Try changing the type of the column from `Number` to `Money`
- Click Save
- Notice the error.

### LINKED ISSUE #4423: Improve Money Inference
When determining whether a given column can be cast to money, we should use the new process:

- Use our `msar.get_money_array(text)` function on a sample of rows to find a grouping separator, decimal separator, currency prefix, and currency suffix.
- Make sure found _at most one_ of each part was found.
- pass those to the new `msar.cast_to_mathesar_money(text, "char", "char", text, text)` function created in #4424 to make sure we can cast a (larger) sample of rows to `msar.mathesar_money` successfully using those assumptions.
- Return info about what grouping and decimal separators were found, what currency symbols were found, and the fact that the column could be cast to money.

### LINKED ISSUE #4424: Add arguments to DB-layer `cast_to_mathesar_money(text)`
For safety, the old `msar.cast_to_mathesar_money(text)` function has to do a regex for each line to:

- determine whether it contains a number,
- determine whether it also has at least one non-number symbol before or after the number, and
- guess the locale to actually cast it to said number.

This is _super_ slow and pretty brittle:
- regex for each line is slow
- Locale is determined per-line, meaning we can't (for example) handle `'$1,000'` vs. `'$1.000'`. The resulting number from casting those strings is locale-dependent.
- We end up casting each line using an independently-determined locale, leading to confusing results.
- We strip off currency symbols line-by-line, but this is lossy when one line may be Euros, and the other Dollars.

We should add a function with the signature:

```
msar.cast_to_mathesar_money(num text, group_sep "char", decimal_p "char", curr_pref text, curr_suff text) RETURNS mathesar_types.mathesar_money
```
This function should do minimal processing and validation. It should just strip out the grouping separator, strip out any currency pre/suffixes, and replace the `decimal_p` when found with the DB-locale decimal point.

### PR DESCRIPTION
**Pull request by Anish9901**
Fixes #4424
Fixes #4423
Fixes #3954

This PR:
- Adds a fast function for casting_to_mathesar_money
  ```plpgsql
  msar.cast_to_mathesar_money(num text, group_sep "char", decimal_p "char", curr_pref text, curr_suff text) RETURNS mathesar_types.mathesar_money
  ```
  currently it is only used for inference but will soon be used for casting the entire column during import preview, once we hook it up with the python layer.
-  Adds `mathesar_money` to the inference array.
-  Modifies the regex in `get_mathesar_money_array` to additionally match data without currency symbols.
- Handles negative currency values.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `develop` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by Anish9901** [comment]
@mathemancer please merge #4452 before reviewing this PR, So that the CI succeeds.

File: db/sql/45_msar_type_casting.sql [hunk 1]
```diff
@@ -745,18 +745,65 @@ DECLARE
...
+                            period_separator_opt_decimal,
+                            space_separator_opt_decimal,
+                            comma_separator_lakh_system
+                          );
+  inner_number_group text := '(' || inner_number_tree || ')';/* Numbers without currency,
+  including inner_number_group as its own capturing group in the money_finding_regex allows us to
+  match columns without any currency symbols allowing users the flexibility
+  to add currency prefixes and suffixes afterwards in the cases of type inference/data imports. */
+  required_currency_beginning text := non_numeric || inner_number_group || non_numeric || '?';
+  required_currency_ending text := non_numeric || '?' || inner_number_group || non_numeric;
```
Comment (mathemancer) [inline db/sql/45_msar_type_casting.sql:776]: Thanks for doing this.

File: db/sql/45_msar_type_casting.sql [hunk 2]
```diff
@@ -745,18 +745,65 @@ DECLARE
...
-  SELECT array_remove(ARRAY[raw_arr[2],raw_arr[3],raw_arr[5],raw_arr[7],raw_arr[9],raw_arr[11],raw_arr[13],raw_arr[15],raw_arr[17],raw_arr[18],raw_arr[20],raw_arr[22],raw_arr[24],raw_arr[26],raw_arr[28],raw_arr[30]], null) INTO decimal_point_arr;
+  SELECT array_remove(ARRAY[
+    raw_arr[1], -- required_currency_beginning[x]
+    raw_arr[16], -- required_currency_ending[x+15]
+    raw_arr[31] -- inner_number_group[x+30]
+  ], null) INTO actual_number_arr;
+  SELECT array_remove(ARRAY[
+    raw_arr[4],raw_arr[6],raw_arr[8],raw_arr[10],raw_arr[12],raw_arr[14], -- required_currency_beginning[x]
+    raw_arr[19],raw_arr[21],raw_arr[23],raw_arr[25],raw_arr[27],raw_arr[29], -- required_currency_ending[x+15]
+    raw_arr[34],raw_arr[36],raw_arr[38],raw_arr[40],raw_arr[42],raw_arr[44] -- inner_number_group[x+30]
```
Comment (mathemancer) [inline db/sql/45_msar_type_casting.sql:791]: Fantastic comments, thanks for that.

File: db/sql/45_msar_type_casting.sql [hunk 3]
```diff
@@ -745,18 +745,65 @@ DECLARE
...
+  ], null) INTO group_divider_arr;
+  SELECT array_remove(ARRAY[
+    raw_arr[2],raw_arr[3],raw_arr[5],raw_arr[7],raw_arr[9],raw_arr[11],raw_arr[13],raw_arr[15], -- required_currency_beginning[x]
+    raw_arr[17],raw_arr[18],raw_arr[20],raw_arr[22],raw_arr[24],raw_arr[26],raw_arr[28],raw_arr[30], -- required_currency_ending[x+15]
+    raw_arr[32],raw_arr[33],raw_arr[35],raw_arr[37],raw_arr[39],raw_arr[41],raw_arr[43],raw_arr[45] -- inner_number_group[x+30]
```
Comment (mathemancer) [inline db/sql/45_msar_type_casting.sql:796]: Good

File: db/sql/45_msar_type_casting.sql [hunk 4]
```diff
@@ -745,18 +745,65 @@ DECLARE
...
+  ], null) INTO decimal_point_arr;
   SELECT actual_number_arr[1] INTO actual_number;
   SELECT group_divider_arr[1] INTO group_divider;
   SELECT decimal_point_arr[1] INTO decimal_point;
-  RETURN ARRAY[actual_number, group_divider, decimal_point, replace($1, actual_number, '')];
+  SELECT replace(replace(split_part($1, actual_number, 1), '-', ''), '(', '') INTO currency_prefix;
+  SELECT replace(replace(split_part($1, actual_number, 2), '-', ''), ')', '') INTO currency_suffix;
+  IF $1::text ~ '^.*(-|\(.+\)).*$' THEN -- Handle negative values
```
Comment (mathemancer) [inline db/sql/45_msar_type_casting.sql:803]: I didn't remember we were handling `(324)` as negative! Cool.

**Review by mathemancer — APPROVED** [review]
This looks really great. Thanks for the helpful comments, and the tests.
