### PR TITLE
Fix Save button not enabling while editing exploration name or description

### LINKED ISSUE #4723: "Save" button for Explorations looks disabled when exploration name or description is changed.
## To Reproduce

- Create an exploration.
- Change its name or description from the inspector
- Notice the "Save" button is still disabled.
- Click the "Save" button, notice that saving works as expected, even though the button seemed disabled.

https://github.com/user-attachments/assets/51c11891-eae6-49f0-8f57-19c4aad72d18

## Expected behavior

Save button should look active when Exploration name or description is altered.

### PR DESCRIPTION
**Pull request by Ahamed1846**
Fixes #4723

This PR fixes a UX issue in the Exploration inspector where the **Save** button appeared disabled while editing the exploration name or description. Although changes were being made, the Save button only became enabled after the input lost focus, which was confusing and made it seem like edits were not being detected.

### Problem

The Save button relies on a `hasChanges` flag to reflect unsaved edits.

Previously:
- `hasChanges` was updated only on the `change` event
- `change` fires only after the input loses focus
- While typing, the Save button remained visually disabled

This caused a mismatch between user actions and UI feedback.

### Fix

- Updated the **name** and **description** inputs to mark the form as changed on the `input` event
- Preserved existing change handlers to avoid altering save behavior

This ensures the Save button reflects unsaved changes immediately while typing.

### Behavior changes

- Save button enables as soon as the user starts typing
- Visual state now accurately reflects pending edits
- No changes to save logic or backend behavior

### Files touched

- `mathesar_ui/src/systems/data-explorer/exploration-inspector/ExplorationTab.svelte`

---

## Checklist
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `develop` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [X] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

File: mathesar_ui/src/systems/data-explorer/exploration-inspector/ExplorationTab.svelte [hunk 1]
```diff
@@ -120,8 +122,10 @@
         <TextArea
           value={description}
           aria-label={$_('description')}
-          on:change={handleDescriptionChange}
-          on:input={setHasChangesToTrue}
+          on:input={(e) => {
+            setHasChangesToTrue();
+            handleDescriptionChange(e);
+          }}
```
Comment (pavish) [inline mathesar_ui/src/systems/data-explorer/exploration-inspector/ExplorationTab.svelte]: The name and description update should happen after a debounced interval when the user is typing and it should immediately happen when the input loses focus. Please use the `Debounce` component from our component library to do this.

**Review by pavish — CHANGES_REQUESTED** [review]

File: mathesar_ui/src/systems/data-explorer/exploration-inspector/ExplorationTab.svelte (hunk 1 above)
Comment (Ahamed1846) [reply mathesar_ui/src/systems/data-explorer/exploration-inspector/ExplorationTab.svelte]: Updated the name and description inputs to use the Debounce component, with debounced updates during typing and immediate updates on blur.

**Review by pavish — APPROVED** [review]
@Ahamed1846 Thanks for the PR!

I added a small commit https://github.com/mathesar-foundation/mathesar/pull/5137/changes/c764cd41ea624717596364ccd7a831ba8eed78f8 that fixes a regression when the name input is cleared.
