### PR TITLE
Fixes i18n bugs

### LINKED ISSUE #3359: i18n bugs
## Description
This issue tracks any i18n bugs that are noticed in the app.

- Dropdown in TableCard displays `Edit [tableName] Table`. Related key: `edit_table`.
- Import preview page type selector and Column Inspector do not display database type. Related key: `database_type_displayer`.
- Breadcrumb search displays raw plural dsl when the search result returns a single item. Related key: `number_of_matches`.

### PR DESCRIPTION
**Pull request by pavish**
Fixes #3359 

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `develop` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by pavish** [comment]
@seancolsen Since this is a small straight-forward PR, I'm going to merge it in as soon as the workflows succeed. Please feel free to take a look post-merge.

File: mathesar_ui/src/components/abstract-type-control/DbTypeIndicator.svelte [hunk 1]
```diff
@@ -1,17 +1,12 @@
...
   export let type: DbType | undefined;
 </script>
 
 <div>
-  <RichText text={$_('database_type_displayer')} let:slotName>
-    {#if slotName === 'format'}
-      <span>{type ?? 'UNKNOWN'}</span>
-    {/if}
-  </RichText>
+  {$_('database_type')}: <span>{type ?? 'UNKNOWN'}</span>
```
Comment (seancolsen) [inline mathesar_ui/src/components/abstract-type-control/DbTypeIndicator.svelte:9]: This seems like it ought to be one string like `Database type: {databaseType}`

Comment (pavish) [reply mathesar_ui/src/components/abstract-type-control/DbTypeIndicator.svelte:9]: @seancolsen I separated them since this content appears in contexts similar to a form. Eg., `Name: <TextInput value={name} />`. I don't feel strongly about either option and I'm fine with both, we could make it into a single string if you feel strongly about it.

Comment (seancolsen) [reply mathesar_ui/src/components/abstract-type-control/DbTypeIndicator.svelte:9]: I see what you mean. I certainly don't feel strongly about this, I just thought that was best practice. Maybe I'm wrong though. I see what you mean about it looking like a form. I guess it's fine since it's not like this is a complete sentence. I'll defer to you. It would be great to eventually have a guide for our devs that clarifies our best practice around some of the edge cases like this.

Comment (pavish) [reply mathesar_ui/src/components/abstract-type-control/DbTypeIndicator.svelte:9]: > It would be great to eventually have a guide for our devs that clarifies our best practice around some of the edge cases like this.

Agreed. I intend to work on the guide once the remaining i18n work is complete.
