### PR TITLE
Fix not null SQL

### LINKED ISSUE #4528: Regression: Unable to set NULL/not NULL on columns that are not in the public schema
## Description
- Open a table in any schema, other than public.
- Check or uncheck the `Disallow NULL values` checkbox in a column with values.
- Notice that there's an error.
- This is a regression on our current `develop` branch.

## Error
```
{
    "id": 0,
    "jsonrpc": "2.0",
    "error": {
        "code": -30259,
        "message": "UndefinedTable: relation \"Exhibits\" does not exist\nCONTEXT:  SQL statement \"ALTER TABLE \"Exhibits\" ALTER COLUMN name DROP NOT NULL\"\nPL/pgSQL function __msar.exec_ddl(text) line 10 at EXECUTE\nPL/pgSQL function __msar.exec_ddl(text,anyarray) line 14 at RETURN\nSQL function \"set_not_null\" statement 1\nSQL statement \"SELECT msar.set_not_null(tab_id, col.attnum, col.not_null)\"\nPL/pgSQL function msar.alter_columns(oid,jsonb) line 40 at PERFORM"
    }
}
```
The schema name doesn't seem to be appended to the query that's executed.

### PR DESCRIPTION
**Pull request by Anish9901**
Fixes #4528

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `develop` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

File: db/sql/test_sql_functions.sql [hunk 1]
```diff
@@ -1995,11 +1998,11 @@ DECLARE
...
 BEGIN
   PERFORM __setup_column_alter();
-  RETURN NEXT is(msar.alter_columns('col_alters'::regclass::oid, col_alters_jsonb), ARRAY[2, 3, 4]);
-  RETURN NEXT col_type_is('col_alters', 'col1', 'character varying(48)');
-  RETURN NEXT col_type_is('col_alters', 'col2', 'integer');
-  RETURN NEXT col_default_is('col_alters', 'col2', 5);
-  RETURN NEXT col_type_is('col_alters', 'Col sp', 'integer');
+  RETURN NEXT is(msar.alter_columns('test_schema.col_alters'::regclass::oid, col_alters_jsonb), ARRAY[2, 3, 4]);
+  RETURN NEXT col_type_is('test_schema', 'col_alters', 'col1', 'character varying(48)', 'type should be varchar');
+  RETURN NEXT col_type_is('test_schema', 'col_alters', 'col2', 'integer', 'type should be integer');
```
Comment (Anish9901) [inline db/sql/test_sql_functions.sql:2003]: I had to include descriptions for certain tests so that the functions resolve to the correct overload.

File: db/sql/test_sql_functions.sql [hunk 2]
```diff
@@ -1922,7 +1922,8 @@ $f$ LANGUAGE plpgsql;
 
 CREATE OR REPLACE FUNCTION __setup_column_alter() RETURNS SETOF TEXT AS $$
 BEGIN
-  CREATE TABLE col_alters (
+  CREATE SCHEMA test_schema;
```
Comment (mathemancer) [inline db/sql/test_sql_functions.sql:1925]: Nice

**Review by mathemancer — APPROVED** [review]
LGTM.
