### PR TITLE
Fix `JSON(B)` & `JSON(B)[]` rendering for table page and data explorer

### LINKED ISSUE #4733: JSON(B) columns show `[object Object]` in Data Explorer
## Description

JSON and JSON(B) columns are broken in Data Explorer, resulting in displaying `[object Object]`.

## Expected behavior

They should display properly (i.e., as JSON).

## To Reproduce

Add a JSON or JSON(B) column to a table, and create a data exploration of that table.

## Additional context

We failed to fix this in #4641, since that fix only applies to non-deprecated code that actually uses the repaired DB functions.

### LINKED ISSUE #4742: Rendering for JSON(B)[] columns break in table page and data explorer
## To Reproduce

- Create a table with a `jsonb[]` column 
```
CREATE TABLE items (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    tags JSONB[]                       
);
```
- Insert some values
```
INSERT INTO items(tags) VALUES
    (ARRAY['{"a":1}'::jsonb, '{"b":2}'::jsonb]),
    (ARRAY['{"x":10, "y":20}'::jsonb]),
    (ARRAY['{"nested":{"k":"v"}}'::jsonb, '{"list":[1,2,3]}'::jsonb, '[2,3,4]'::jsonb]);;
```
- Navigate to the table page for `items` from mathesar and notice the rendering:
Image

## Expected behavior
The rendering shouldn't break.

## Additional context

Related to #4641, #1324, #4733

### PR DESCRIPTION
**Pull request by Anish9901**
Fixes #4733
Fixes #4742  

**Screenshots**

Screenshot 2025-09-05 at 11 15 21 PM
Screenshot 2025-09-05 at 11 13 48 PM
Screenshot 2025-09-05 at 11 12 57 PM

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `develop` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

File: db/sql/05_msar.sql [hunk 1]
```diff
@@ -4320,11 +4320,21 @@ SELECT val::text;
 $$ LANGUAGE SQL IMMUTABLE RETURNS NULL ON NULL INPUT PARALLEL SAFE;
 
 
+CREATE OR REPLACE FUNCTION msar.format_data(val jsonb[]) returns jsonb AS $$
+SELECT jsonb_agg(x::text) FROM unnest(val) AS x;
```
Comment (mathemancer) [inline db/sql/05_msar.sql]: Why not aggregate to an array? That would be more consistent with the data explorer experience. So, the output would be `text[]`.

File: db/deprecated/utils.py [hunk 2]
```diff
@@ -27,11 +28,26 @@ def execute_statement(engine, statement, connection_to_use=None):
...
+        if isinstance(col.type, (JSONB, JSON)):
+            col_list.append(sqlalchemy.cast(col, TEXT))
+        elif isinstance(col.type, ARRAY) and isinstance(col.type.item_type, (JSONB, JSON)):
+            new_col = sqlalchemy.literal_column(
+                f"(SELECT jsonb_agg(x::text) FROM unnest({str(col)}) AS x)"
+            ).label(col.name)
+            col_list.append(new_col)
+        else:
+            col_list.append(col)
+    return col_list
```
Comment (mathemancer) [inline db/deprecated/utils.py]: Letting all the `isinstance` calls pass since this is in the deprecated.

This should use `array_agg` instead of `jsonb_agg`.

**Review by mathemancer — APPROVED** [review]
Nice work overall. However, I'd really prefer you use `array_agg` rather than `jsonb_agg` (or `json_agg`), since that's more consistent with the other column types.

**Comment by Anish9901** [comment]
@mathemancer I updated the functions to use `::text[]` instead of using `unnest` and `agg`. I'll merge this now, please review retroactively.
