### PR TITLE
Reduces frontend caching, fixes a few bugs

### LINKED ISSUE #3864: Handle privilege change side-effects when modifying collaborators and roles
## Description
* There are cases where a refetching of privileges might be required due to indirect changes such as modifying the collaborator role. Some of them:
  * When the collaborator role changes and if it's for current logged in user.
  * When the roles are modified with `.setMembers` and `.delete`:
* The following needs to be done during those scenarions:
    - Implement refetching database permissions
    - Refetch schemas list
    - Clear tables (if it's present)
* A broader discussion might be required on reducing caching on the frontend.

### LINKED ISSUE #3877: Cached schemas & roles still displayed after admin removes themselves as a Collaborator
## Description
* Create a database.
* Remove yourself as the collaborator.
* Notice that schemas and roles being displayed.
* Refresh the page. Notice a `DoesNotExist: UserDatabaseRoleMap matching query does not exist.` error.

### PR DESCRIPTION
**Pull request by pavish**
Fixes #3864
Fixes #3877
Reduces frontend caching: Only caches current schema, tables, and explorations
Fixes duplicate requests for `databases.get`
Fixes common data: Null scenarios, removes abstract types
Fixes some minor translation issues (see commits)

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `develop` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

File: mathesar_ui/src/pages/database/settings/collaborators/CollaboratorRow.svelte [hunk 1]
```diff
@@ -7,11 +7,13 @@
   import { iconDeleteMajor, iconEdit } from '@mathesar/icons';
   import type { Collaborator } from '@mathesar/models/Collaborator';
   import { confirmDelete } from '@mathesar/stores/confirmation';
+  import { toast } from '@mathesar/stores/toast';
   import { getUserProfileStoreFromContext } from '@mathesar/stores/userProfile';
   import { Button, SpinnerButton } from '@mathesar-component-library';
 
   export let collaborator: Collaborator;
   export let editRoleForCollaborator: (collaborator: Collaborator) => void;
+  export let checkAndHandleSideEffects: (collaboror: Collaborator) => void;
```
Comment (seancolsen) [inline mathesar_ui/src/pages/database/settings/collaborators/CollaboratorRow.svelte:16]: I suggest renaming `checkAndHandleSideEffects` to `onDelete`.

**Review by seancolsen — APPROVED** [review]
This is really great. I like how the changes in `stores/*` simplify a lot of things!

Instead of requesting changes, I just made them myself, and I'll kick this back to you to look over before merging. If you don't like my changes, we can continue discussing. Or if you're cool with this, then feel free to merge.

There was some naming I didn't like, so I pushed 2c39ff9229700115cd76a79f52c21bec01bb4afc to adjust it.

Those naming changes also led me to dig deeper into `AsyncRpcApiStore.runBatched` because I especially didn't like using the word "optimal" to refer to the logic of running something only when it's not initialized. The word "optimal" made me think it would always run but that it would do so using some special heuristics like compression or something. I think "conservative" is a better word (though not perfect) to indicate that it will happen only when necessary.

Also, we don't currently have a need for `AsyncRpcApiStore` to handle arrays of BatchRunners with different modes. If we did have such a need, then passing an array of runners alongside an array of options would seem messy and hard to read because the options would not be lined up directly with their runners. This is the sort of code that I would not love:

```ts
AsyncRpcApiStore.runBatch(
  [
    foo.batchRunner({ a: 1 }),
    bar.batchRunner({ b: 2 }),
  ],
  { mode: [ 'force-run', 'optimal' ] }
);
```

If we do eventually have a need for one batch with different modes like that, then I'd rather make some minor modifications to allow calling code that would look something like this:

```ts
AsyncRpcApiStore.runBatch([
  foo.batchRunner({ a: 1 }),
  bar.conservativeBatchRunner({ b: 2 }),
]);
```

But we don't even have that need yet, so I think it's best to err on the side of simplicity and only support batching via homogeneous modes.

**Comment by pavish** [comment]
Thanks @seancolsen!

I think the name changes make sense.

I added two small commits.
- https://github.com/mathesar-foundation/mathesar/pull/3897/commits/4291b3b96985f40a575f0270ea057239abdf4068 to make the logic consistent between `runConservatively` and `runBatchConservatively`.
- https://github.com/mathesar-foundation/mathesar/pull/3897/commits/98e48eab1534c24b4c6734040270f5e298b75b4b to run side effects when the logged in user adds themselves as a collaborator.

I'm going to merge this PR in since the commits are fairly minor. Please feel free to take a look and review retroactively.
