### PR TITLE
Fix primary key recognition when column has multiple indexes

### LINKED ISSUE #4656: Additional index on table breaks Mathesar's primary key recognition
## Description

Using the following table and constraints:

```sql
CREATE TABLE public.index_test (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    col_a text NOT NULL
);

-- Primary Key
ALTER TABLE public.index_test
    ADD CONSTRAINT index_test_pkey PRIMARY KEY (id);

-- Index on col_a and id
CREATE INDEX ix_index_test_col_a_id ON public.index_test (col_a, id);

```

Mathesar does not detect this table as having a Primary key:

Image

Removing the `ix_index_test_col_a_id` index fixes the problem.

## Expected behavior

Mathesar correctly identifies the table's primary key.

## To Reproduce

Load this SQL into a local Mathesar instance (`docker exec -it mathesar_dev_db psql -U mathesar`) and verify the behavior.

### PR DESCRIPTION
**Pull request by zackkrida**
Fixes #4656 

**Technical details**

This PR fixes #4656 by adding an `AND pgi.indisprimary` check to the left join in `msar.column_info_table`. Previously, a primary key column that also had a unique index would appear multiple times in the result.

I added a new test as well. 

**Screenshots**

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `develop` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

File: db/sql/test_sql_functions.sql [hunk 1]
```diff
@@ -3044,6 +3044,41 @@ END;
 $$ LANGUAGE plpgsql;
 
 
+CREATE OR REPLACE FUNCTION test_get_column_info_with_multiple_indexes() RETURNS SETOF TEXT AS $$/*
+Regression test for issue #4656: get_column_info returned duplicate column entries when a column
```
Comment (mathemancer) [inline db/sql/test_sql_functions.sql]: This comment isn't really necessary, though I'm more forgiving of the over-commenting habit in tests.

**Review by mathemancer — APPROVED** [review]
Code looks good, test looks good. Nice work!

I'd prefer you remove the extraneous comments in the test before merging, but I'll leave that up to you.

File: db/sql/test_sql_functions.sql (hunk 1 above)
Comment (zackkrida) [reply db/sql/test_sql_functions.sql]: Removed in 0799b3e09.
