### PR TITLE
Drop schema contents when deleting

### LINKED ISSUE #4240: Unable to delete schemas
## Description
- Create a new database, use the existing 'Bike Shop' schema.
- Now try to delete the schema.
- It fails with the following error.

> Unable to delete Schema. DependentObjectsStillExist: cannot drop schema Bike Shop because other objects depend on it DETAIL: table "Bike Shop"."Customers" depends on schema Bike Shop table "Bike Shop"."Equipment" depends on schema Bike Shop table "Bike Shop"."Equipment Types" depends on schema Bike Shop table "Bike Shop"."Mechanics" depends on schema Bike Shop table "Bike Shop"."Service Milestones" depends on schema Bike Shop table "Bike Shop"."Service Requests" depends on schema Bike Shop table "Bike Shop"."Service Statuses" depends on schema Bike Shop HINT: Use DROP ... CASCADE to drop the dependent objects too. CONTEXT: SQL statement "DROP SCHEMA "Bike Shop"" PL/pgSQL function msar.drop_schema(text,boolean) line 13 at EXECUTE SQL statement "SELECT msar.drop_schema(msar.get_schema_name(sch_id), cascade_)" PL/pgSQL function msar.drop_schema(oid,boolean) line 11 at PERFORM

## Expected result
- We should be able to delete schemas

### PR DESCRIPTION
**Pull request by mathemancer**
Fixes #4240 

Modifies the `schemas.delete` RPC function to drop all objects within passed schemas, and then the schemas themselves, _without_ `CASCADE`.

**Technical details**

- This is far safer than `CASCADE`, but lets users delete schemas that still contain objects
- The new version of the function accepts an _array_ of schema OIDs to drop. 
  - This allows for future UIs where we allow a user to drop a set of schemas containing interdependent objects
- The error messaging is greatly improved so that if a schema to be dropped contains dependencies of a schema which _isn't_ to be dropped, all dependency issues will be shown.
- I updated the scenario test so that it would have failed with the previous version.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `develop` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by mathemancer** [comment]
@pavish I made very tiny FE changes, so I assigned you to look at those.

File: mathesar_ui/src/models/Schema.ts [hunk 1]
```diff
@@ -102,7 +102,7 @@ export class Schema {
     return api.schemas
       .delete({
         database_id: this.database.id,
-        schema_oid: this.oid,
+        schema_oids: [this.oid],
```
Comment (pavish) [inline mathesar_ui/src/models/Schema.ts:105]: Looks great.

**Review by pavish — CHANGES_REQUESTED** [review]

**Review by pavish — APPROVED** [review]
LGTM!

File: db/sql/test_sql_functions.sql [hunk 2]
```diff
@@ -1312,6 +1328,87 @@ END;
...
+        ('projects', 'actors_copy', 'VIEW'),
+        ('projects', 'movies_pkey', 'INDEX')
+      $v$,
+      'msar.get_schema_objects_table() should return objects for multiple schemas'
+  );
+END;
+$$ LANGUAGE plpgsql;
+
+
+CREATE OR REPLACE FUNCTION test_drop_schemas_single() RETURNS SETOF TEXT AS $$
```
Comment (Anish9901) [inline db/sql/test_sql_functions.sql:1388]:
```suggestion
CREATE OR REPLACE FUNCTION test_drop_single_schema_with_dependent_objs() RETURNS SETOF TEXT AS $$
```

File: db/sql/05_msar.sql [hunk 3]
```diff
@@ -698,6 +698,55 @@ END;
...
+        WHEN 'v' THEN 'VIEW'
+        WHEN 'm' THEN 'MATERIALIZED VIEW'
+        WHEN 'c' THEN 'TYPE'
+        WHEN 'f' THEN 'FOREIGN TABLE'
+      END AS obj_kind
+    FROM pg_class
+    WHERE relnamespace=ANY(schemas)
+  )
+) SELECT DISTINCT obj_id, obj_schema, obj_name, obj_kind FROM obj_cte WHERE obj_kind IS NOT NULL;
+$$ LANGUAGE SQL;
```
Comment (Anish9901) [inline db/sql/05_msar.sql:747]: Shouldn't this be `STABLE` & return null on null input?

```suggestion
$$ LANGUAGE SQL STABLE RETURNS NULL ON NULL INPUT;
```

Comment (mathemancer) [reply db/sql/05_msar.sql:747]: Sure, that works.
