### PR TITLE
Fix record ordering for non-orderable PostgreSQL types

### LINKED ISSUE #1321: Unable to load records with circle column type
## Reproduce

1. Execute this SQL

    ```sql
    DROP TABLE IF EXISTS "type_test";
    CREATE TABLE "type_test" (
        "id" serial NOT NULL,
        "circle" circle
    );
    INSERT INTO "type_test" ("circle") VALUES ('<(1, 2), 3>');
    ```

1. Try to load that table.

1. Observe an API request to `/api/db/v0/tables/{id}/records/`

1. Expect a successful response.

1. Observe the following response:

    ```json
    [
      {
        "code": 4207,
        "message": "could not identify an ordering operator for type circle",
        "field": null,
        "detail": "could not identify an ordering operator for type circle"
      }
    ]
    ```

### PR DESCRIPTION
**Pull request by mosesacknals139**
Fixes #1321 

This PR fixes an issue where tables containing `circle` columns failed to load due to invalid ordering logic. The update ensures that only columns supporting deterministic ordering are used when constructing ORDER BY clauses.

**Technical details**

The root cause was that `msar.get_total_order` previously allowed column types without valid B-Tree operator support (such as `circle`) to be included in the ordering logic. This caused SQL errors when PostgreSQL attempted to apply ordering on unsupported data types.

The function has been updated to strictly validate orderable columns by:

- Enforcing use of the `btree` access method via `pg_am`
- Requiring `opcdefault = true` to ensure default operator classes only
- Supporting both `opcintype` and `opckeytype` for correct operator resolution
- Eliminating duplicate column entries using `SELECT DISTINCT`
- Include types that are binary coercible to types with b-trees

**Updated file**
- `db/sql/05_msar.sql`

**Verification**
- Confirmed that tables containing `circle` columns now load correctly.
- Verified that the system falls back to valid sortable columns (such as primary keys) without error.

**Screenshots**
before
image

after
image

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `develop` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

File: db/sql/05_msar.sql [hunk 1]
```diff
@@ -4427,31 +4427,31 @@ $$ LANGUAGE SQL STABLE RETURNS NULL ON NULL INPUT;
...
+    )
+    INNER JOIN pg_catalog.pg_am ON opcmethod = pg_am.oid
   WHERE
     attrelid = tab_id
     AND attnum > 0
     AND NOT attisdropped
-    AND oprname = '<'
+    AND amname = 'btree'
+    AND opcdefault = true
+    AND has_column_privilege(tab_id, attnum, 'SELECT')
```
Comment (mathemancer) [inline db/sql/05_msar.sql:4450]: Nice

**Review by mathemancer — APPROVED** [review]
LGTM.
