### PR TITLE
Fix/4895 record summary template references deleted column

### LINKED ISSUE #4895: Error when listing records if record summary template references a deleted column
## Steps to reproduce

1. Begin with the following sample data:

    ```sql
    create table issue_4895 (
      id int primary key generated always as identity,
      a text,
      b text,
      parent int
    );
    insert into issue_4895 (a, b, parent) values
    ('foo', 'bar', NULL),
    ('baz', 'bat', 1);
    alter table issue_4895 add constraint issue_4895_parent_fkey
    foreign key (parent) references issue_4895 (id);
    ```

1. Open the table page for `issue_4895`.

1. Select the "foo" FK cell, and configure the Linked Record Summary to display both `a` and `b` columns.

    Image

    Save.

1. Now delete column `b` from the table.

1. Expect the sheet to load, displaying "foo" as the record summary for the linked record. Because the "bar" value from column `b` is no longer available, it should be silently ignored.

1. Notice that when the sheet reloads, there is an error.

    Image

    Although this error is not shown to the user, you can see it in the network tab of your dev tools if you find the request to the `records.list` API:

    > UndefinedColumn: column base.........pg.dropped.3........ does not exist
    > LINE 15: || COALESCE(msar.format_data(base."........pg.dropped.3....
    >  ^
    > QUERY: 
    >  WITH
    >  count_cte AS ( SELECT count(1) AS count FROM public.issue_4895 ),
    >  enriched_results_cte AS ( SELECT msar.format_data(id) AS "1", msar.format_data(a) AS "2", msar.format_data(parent) AS "4", NULL AS __mathesar_gid, NULL AS __mathesar_gcount FROM public.issue_4895 ORDER BY "1" ASC LIMIT '5… jsonb_build_array()
    >  )
    >  ,
    >  'count', coalesce(max(count_cte.count), 0),
    >  'grouping', NULL
    >  ) AS rj
    >  FROM enriched_results_cte
    >  LEFT JOIN groups_cte ON enriched_results_cte.__mathesar_gid = groups_cte.id
    >  CROSS JOIN count_cte
    >  )
    >  SELECT records_json_cte.rj || summaries_json_cte.sj
    >  FROM records_json_cte, summaries_json_cte;
    >  
    > CONTEXT: PL/pgSQL function msar.list_records_from_table(oid,integer,integer,jsonb,jsonb,jsonb,boolean,jsonb) line 31 at EXECUTE

### PR DESCRIPTION
**Pull request by wbonicki**
Fixes #4895

The PR fixes bug with listing records if record summary template references a deleted colum.
**Technical details**

Two sql functions were changed:
1. get_column_name - added condition that checks if att is dropped
2. build_record_summary_query_from_template - added checks to skip dropped or non-selectable columns and fixed incorrect privilege validation on the final referenced column (ref_col_id) to prevent invalid SQL generation
**Screenshots**

image
image

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `develop` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable). (not applicable in this case)
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

File: db/sql/05_msar.sql [hunk 1]
```diff
@@ -397,7 +397,7 @@ Args:
   rel_id:  The OID of the relation.
   col_id:  The attnum of the column in the relation.
 */
-SELECT attname::text FROM pg_attribute WHERE attrelid=rel_id AND attnum=col_id;
+SELECT attname::text FROM pg_attribute WHERE attrelid=rel_id AND attnum=col_id AND NOT attisdropped;
```
Comment (Anish9901) [inline db/sql/05_msar.sql:400]: Looks good! We also have an overload of this function `msar.get_column_name(rel_id oid, col_name text)` which we don't use as much. But, It would be good to have the behavior consistent for the overload as well.

Also, in the docstring for both the function please mention that we would only return the name of attributes that aren't dropped.

File: db/sql/05_msar.sql [hunk 2]
```diff
@@ -4979,6 +4978,10 @@ BEGIN
         END LOOP;
 
         ref_col_id := ref_chain[ref_chain_length];
+        ref_col_name := msar.get_column_name(contextual_tab_id, ref_col_id);
+        IF ref_col_name IS NULL THEN
+          CONTINUE template_parts_loop;
+        END IF;
```
Comment (Anish9901) [inline db/sql/05_msar.sql]: Seems redundant, we check whether `ref_col_name IS NOT NULL` after a couple of lines. Please revert this.

File: db/sql/05_msar.sql [hunk 3]
```diff
@@ -4926,17 +4926,14 @@ BEGIN
...
             END IF;
 
-            fk_col_name := msar.get_column_name(contextual_tab_id, fk_col_id);
-
-            IF fk_col_name IS NULL THEN
-              -- Silently ignore references to non-existing FK columns. This can happen if a column
-              -- has been deleted.
+            IF NOT pg_catalog.has_column_privilege(contextual_tab_id, fk_col_id, 'SELECT') THEN
               CONTINUE template_parts_loop;
             END IF;
```
Comment (Anish9901) [inline db/sql/05_msar.sql]: What does this change achieve? Also, those comments that you removed are useful to know why the checks were added in the first place, why remove it?

File: db/sql/05_msar.sql [hunk 4]
```diff
@@ -4945,8 +4942,11 @@ BEGIN
...
             IF ref_tab_id IS NULL THEN
-              -- Silently ignore references to non-FK columns. This can happen if the constraint
-              -- has been dropped.
+              CONTINUE template_parts_loop;
+            END IF;
+
+            ref_col_name := msar.get_column_name(ref_tab_id, ref_col_id);
+            IF ref_col_name IS NULL THEN
               CONTINUE template_parts_loop;
             END IF;
```
Comment (Anish9901) [inline db/sql/05_msar.sql]: Since `fk_col` is dependent on `ref_col` via a foreign key constraint, it is not possible to drop `ref_col`:
- Without dropping the foreign key constraint. _or_
- Without dropping the dependent cols, `fk_col` in this case.

So, this check is redundant as we will never encounter this scenario. Please revert this.

File: db/sql/test_sql_functions.sql [hunk 5]
```diff
@@ -7323,3 +7323,50 @@ BEGIN
   );
 END;
 $$ LANGUAGE plpgsql;
+
+
+CREATE OR REPLACE FUNCTION test_build_record_summary_query_skips_dropped_column()
```
Comment (Anish9901) [inline db/sql/test_sql_functions.sql]: Please see `test_custom_record_summary_template()` or other record_summary tests and write a similar test which checks that the record summaries are returned without errors and the returned value is as expected, even after dropping the column.

**Review by Anish9901 — CHANGES_REQUESTED** [review]

File: db/sql/05_msar.sql (hunk 1 above)
Comment (wbonicki) [reply db/sql/05_msar.sql:400]: Fixed! Overloaded function as well as docstrings

File: db/sql/05_msar.sql (hunk 3 above)
Comment (wbonicki) [reply db/sql/05_msar.sql]: Reverted to the original version

File: db/sql/05_msar.sql (hunk 4 above)
Comment (wbonicki) [reply db/sql/05_msar.sql]: I cannot remove it, because without this part tests fail (Failed tests:  90, 165, 167, 169 including my test).

File: db/sql/test_sql_functions.sql (hunk 5 above)
Comment (wbonicki) [reply db/sql/test_sql_functions.sql]: Fixed - please check if now it has correct structure. I also moved the test from the end of the file.

File: db/sql/05_msar.sql (hunk 2 above)
Comment (wbonicki) [reply db/sql/05_msar.sql]: removed

File: db/sql/05_msar.sql (hunk 4 above)
Comment (Anish9901) [reply db/sql/05_msar.sql]: Tests failed because `ref_col_name` was removed. Please revert all the changes made in this function(`msar.build_record_summary_query_from_template`). Only the changes you made in `msar.get_column_name` are sufficient to fix #4895.

File: db/sql/test_sql_functions.sql [hunk 6]
```diff
@@ -5414,6 +5414,30 @@ END;
 $$ LANGUAGE plpgsql;
 
 
+CREATE OR REPLACE FUNCTION test_record_summary_after_dropped_referenced_column()
```
Comment (Anish9901) [inline db/sql/test_sql_functions.sql:5449]: Nice test!

File: db/sql/05_msar.sql (hunk 4 above)
Comment (wbonicki) [reply db/sql/05_msar.sql]: Ahh thank you for pointing this out! Fixed!

**Review by Anish9901 — APPROVED** [review]
Looks great after the changes, Thanks for your work on this @wbonicki!
